name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "**"

jobs:
  build:
    strategy:
      matrix:
        name: [Rugby_League_NRF52840, Rugby_League_ESP32S3]
    steps:
      - uses: haobogu/rmk/.github/workflows/user_build.yml@main
        with:
          keyboard_toml_path: "${{ matrix.name }}/keyboard.toml"
          vial_json_path: "${{ matrix.name }}/vial.json"
