name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        kb:
          - { name: Rugby_League_ESP32S3 }
          - { name: Rugby_League_NRF52840 }
    uses: HaoboGu/rmk/.github/workflows/user_build.yml@main
    with:
      keyboard_toml_path: ${{ matrix.kb.name }}/keyboard.toml
      vial_json_path: ${{ matrix.kb.name }}/vial.json
