name: Build Rugby_League_ESP32S3 RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "**"

jobs:
  build:
    uses: haobogu/rmk/.github/workflows/user_build.yml@main
    with:
      keyboard_toml_path: "Rugby_League_ESP32S3/keyboard.toml"
      vial_json_path: "Rugby_League_ESP32S3/vial.json"
